/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg7_hectorreyes;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Onasis Reyes
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        jD_añadirCarro.setTitle("Crear Carros");
        jD_añadirEmpleado.setTitle("Añadir Empleado");
        numEmpleados = 0;
        adminB1 = new AdminBarra1(jPb_barra1);
        adminB2 = new AdminBarra2(jPb_barra2);
        adminB3 = new AdminBarra3(jPb_barra3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jD_añadirCliente = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jCbox_asignarCarroCliente = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jT_nombreCliente = new javax.swing.JTextField();
        jT_apellidoCliente = new javax.swing.JTextField();
        btn_añadirCliente = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTbl_tablaClientes = new javax.swing.JTable();
        jSp_edadCliente = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jD_añadirCarro = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jT_placa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSp_puertas = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jSp_suciedad = new javax.swing.JSpinner();
        jComboBox3 = new javax.swing.JComboBox<>();
        btn_añadirCarro = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jD_AsignarCarroEmpleado = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jCbox_carrosCliente = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbl_carroParaEmpleado = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        btb_aggCarros = new javax.swing.JButton();
        jD_añadirEmpleado = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jT_nombreEmpleado = new javax.swing.JTextField();
        jT_apellido = new javax.swing.JTextField();
        jSp_edadEmpleado = new javax.swing.JSpinner();
        btn_asignarCarroEmpleado = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btn_guardarEmpleado = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPb_barra1 = new javax.swing.JProgressBar();
        jPb_barra2 = new javax.swing.JProgressBar();
        jPb_barra3 = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTbl1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTbl2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTbl3 = new javax.swing.JTable();
        jCbox1 = new javax.swing.JComboBox<>();
        jCbox2 = new javax.swing.JComboBox<>();
        jCbox3 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMI_añadirEmpleado = new javax.swing.JMenu();
        jMI_añadirCliente = new javax.swing.JMenuItem();
        jMI_añadirCarro = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jCbox_asignarCarroCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Asignarle Carro al Cliente");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Nombre");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Apellido");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Edad");

        btn_añadirCliente.setText("Añadir Cliente");
        btn_añadirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_añadirClienteActionPerformed(evt);
            }
        });

        jTbl_tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tamaño", "Nombre", "Apellido", "Carros"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTbl_tablaClientes);
        if (jTbl_tablaClientes.getColumnModel().getColumnCount() > 0) {
            jTbl_tablaClientes.getColumnModel().getColumn(0).setResizable(false);
            jTbl_tablaClientes.getColumnModel().getColumn(1).setResizable(false);
            jTbl_tablaClientes.getColumnModel().getColumn(2).setResizable(false);
            jTbl_tablaClientes.getColumnModel().getColumn(3).setResizable(false);
        }

        jSp_edadCliente.setModel(new javax.swing.SpinnerNumberModel(18, 18, null, 1));

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jT_apellidoCliente)
                            .addComponent(jT_nombreCliente)
                            .addComponent(jCbox_asignarCarroCliente, 0, 130, Short.MAX_VALUE)
                            .addComponent(jSp_edadCliente)
                            .addComponent(btn_añadirCliente, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCbox_asignarCarroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jT_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jT_apellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jSp_edadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_añadirCliente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jD_añadirClienteLayout = new javax.swing.GroupLayout(jD_añadirCliente.getContentPane());
        jD_añadirCliente.getContentPane().setLayout(jD_añadirClienteLayout);
        jD_añadirClienteLayout.setHorizontalGroup(
            jD_añadirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jD_añadirClienteLayout.setVerticalGroup(
            jD_añadirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Número de Placa");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tamaño");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Número de Puertas");

        jSp_puertas.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nivel de Suciedad");

        jSp_suciedad.setModel(new javax.swing.SpinnerNumberModel(5, 5, 10, 1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grande", "Mediano", "Pequeño" }));

        btn_añadirCarro.setText("Añadir Carro");
        btn_añadirCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_añadirCarroActionPerformed(evt);
            }
        });

        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jT_placa)
                            .addComponent(jSp_puertas)
                            .addComponent(jSp_suciedad)
                            .addComponent(jComboBox3, 0, 130, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_añadirCarro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jT_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSp_puertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSp_suciedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btn_añadirCarro)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jD_añadirCarroLayout = new javax.swing.GroupLayout(jD_añadirCarro.getContentPane());
        jD_añadirCarro.getContentPane().setLayout(jD_añadirCarroLayout);
        jD_añadirCarroLayout.setHorizontalGroup(
            jD_añadirCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jD_añadirCarroLayout.setVerticalGroup(
            jD_añadirCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jCbox_carrosCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el Cliente:" }));

        jTbl_carroParaEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número de Placa", "Tamaño", "Número de Puertas", "Nivel de Suciedad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTbl_carroParaEmpleado);
        if (jTbl_carroParaEmpleado.getColumnModel().getColumnCount() > 0) {
            jTbl_carroParaEmpleado.getColumnModel().getColumn(0).setResizable(false);
            jTbl_carroParaEmpleado.getColumnModel().getColumn(0).setHeaderValue("Placa");
            jTbl_carroParaEmpleado.getColumnModel().getColumn(1).setResizable(false);
            jTbl_carroParaEmpleado.getColumnModel().getColumn(1).setHeaderValue("Tamaño");
            jTbl_carroParaEmpleado.getColumnModel().getColumn(2).setResizable(false);
            jTbl_carroParaEmpleado.getColumnModel().getColumn(2).setHeaderValue("Puertas");
            jTbl_carroParaEmpleado.getColumnModel().getColumn(3).setResizable(false);
            jTbl_carroParaEmpleado.getColumnModel().getColumn(3).setHeaderValue("Suciedad");
        }

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Presione sobre el Carro a Lavar:");

        jButton5.setText("Cerrar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btb_aggCarros.setText("Agregar Carros del Cliente");
        btb_aggCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btb_aggCarrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btb_aggCarros)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCbox_carrosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jCbox_carrosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(btb_aggCarros))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jD_AsignarCarroEmpleadoLayout = new javax.swing.GroupLayout(jD_AsignarCarroEmpleado.getContentPane());
        jD_AsignarCarroEmpleado.getContentPane().setLayout(jD_AsignarCarroEmpleadoLayout);
        jD_AsignarCarroEmpleadoLayout.setHorizontalGroup(
            jD_AsignarCarroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jD_AsignarCarroEmpleadoLayout.setVerticalGroup(
            jD_AsignarCarroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Nombre");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Apellido");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Edad");

        jSp_edadEmpleado.setModel(new javax.swing.SpinnerNumberModel(18, 18, null, 1));

        btn_asignarCarroEmpleado.setText("Asignar Carro");
        btn_asignarCarroEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_asignarCarroEmpleadoActionPerformed(evt);
            }
        });

        jButton4.setText("Cerrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btn_guardarEmpleado.setText("Añadir Empleado");
        btn_guardarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(49, 49, 49)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton4)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(btn_guardarEmpleado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_asignarCarroEmpleado)))
                    .addComponent(jSp_edadEmpleado)
                    .addComponent(jT_apellido)
                    .addComponent(jT_nombreEmpleado))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jT_nombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jT_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jSp_edadEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_asignarCarroEmpleado)
                    .addComponent(btn_guardarEmpleado))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jD_añadirEmpleadoLayout = new javax.swing.GroupLayout(jD_añadirEmpleado.getContentPane());
        jD_añadirEmpleado.getContentPane().setLayout(jD_añadirEmpleadoLayout);
        jD_añadirEmpleadoLayout.setHorizontalGroup(
            jD_añadirEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jD_añadirEmpleadoLayout.setVerticalGroup(
            jD_añadirEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 255));
        jLabel10.setText("Carwash");

        jTbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Tamaño", "Puertas", "Suciedad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTbl1);
        if (jTbl1.getColumnModel().getColumnCount() > 0) {
            jTbl1.getColumnModel().getColumn(0).setResizable(false);
            jTbl1.getColumnModel().getColumn(0).setHeaderValue("Placa");
            jTbl1.getColumnModel().getColumn(1).setResizable(false);
            jTbl1.getColumnModel().getColumn(1).setHeaderValue("Tamaño");
            jTbl1.getColumnModel().getColumn(2).setResizable(false);
            jTbl1.getColumnModel().getColumn(2).setHeaderValue("Puertas");
            jTbl1.getColumnModel().getColumn(3).setResizable(false);
            jTbl1.getColumnModel().getColumn(3).setHeaderValue("Suciedad");
        }

        jTbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Tamaño", "Puertas", "Suciedad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTbl2);
        if (jTbl2.getColumnModel().getColumnCount() > 0) {
            jTbl2.getColumnModel().getColumn(0).setResizable(false);
            jTbl2.getColumnModel().getColumn(0).setHeaderValue("Placa");
            jTbl2.getColumnModel().getColumn(1).setResizable(false);
            jTbl2.getColumnModel().getColumn(1).setHeaderValue("Tamaño");
            jTbl2.getColumnModel().getColumn(2).setResizable(false);
            jTbl2.getColumnModel().getColumn(2).setHeaderValue("Puertas");
            jTbl2.getColumnModel().getColumn(3).setResizable(false);
            jTbl2.getColumnModel().getColumn(3).setHeaderValue("Suciedad");
        }

        jTbl3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTbl3);

        jCbox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Empleado:" }));

        jCbox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Empleado:" }));

        jCbox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Empleado:" }));

        jButton2.setText("Simular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(23, 23, 23)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jCbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPb_barra1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(23, 23, 23)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPb_barra2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCbox2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(28, 28, 28)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPb_barra3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCbox3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(jButton2)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel10)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPb_barra3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPb_barra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPb_barra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(jButton2)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        jMI_añadirEmpleado.setText("File");

        jMI_añadirCliente.setText("Añadir Cliente");
        jMI_añadirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_añadirClienteActionPerformed(evt);
            }
        });
        jMI_añadirEmpleado.add(jMI_añadirCliente);

        jMI_añadirCarro.setText("Añadir Carro");
        jMI_añadirCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_añadirCarroActionPerformed(evt);
            }
        });
        jMI_añadirEmpleado.add(jMI_añadirCarro);

        jMenuItem3.setText("Añadir Empleado");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMI_añadirEmpleado.add(jMenuItem3);

        jMenuBar1.add(jMI_añadirEmpleado);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_añadirCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_añadirCarroActionPerformed
        // TODO add your handling code here:
        if (jT_placa.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Porfavor ingrese el número de placa.");
        } else {
            DefaultComboBoxModel cBoxModel = (DefaultComboBoxModel) jCbox_asignarCarroCliente.getModel();
            Carro c = new Carro(
                    jT_placa.getText(),
                    jComboBox3.getSelectedItem().toString(),
                    Integer.parseInt(jSp_puertas.getValue().toString()),
                    Integer.parseInt(jSp_suciedad.getValue().toString()));
            cBoxModel.addElement(c);

            AdministrarCarro adminCar = new AdministrarCarro("./carros.123");
            adminCar.cargarArchivo();
            adminCar.añadirCarro(c);
            adminCar.escribirArchivo();//*/

            jCbox_asignarCarroCliente.setModel(cBoxModel);
            jT_placa.setText("");
        }
    }//GEN-LAST:event_btn_añadirCarroActionPerformed

    private void btn_añadirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_añadirClienteActionPerformed
        // TODO add your handling code here:
        if (jT_nombreCliente.getText().equals("") || jT_apellidoCliente.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Porfavor llene todos los campos.");
        } else if (jCbox_asignarCarroCliente.getItemCount() <= 0) {
            JOptionPane.showMessageDialog(this, "No existen carros para poder crear un cliente.");
        } else if (jCbox_asignarCarroCliente.getSelectedIndex() == 0
                && jCbox_asignarCarroCliente.getItemCount() > 0) {
            JOptionPane.showMessageDialog(this, "Porfavor Selecciona un carro.");
        } else {
            DefaultTableModel tblModel = (DefaultTableModel) jTbl_tablaClientes.getModel();
            DefaultComboBoxModel cBoxmodel = (DefaultComboBoxModel) jCbox_carrosCliente.getModel();
            Cliente c = new Cliente(jT_nombreCliente.getText(),
                    jT_apellidoCliente.getText(),
                    Integer.parseInt(jSp_edadCliente.getValue().toString()));
            c.añadirCarro((Carro) jCbox_asignarCarroCliente.getSelectedItem());

            AdministrarCliente adminC = new AdministrarCliente("./clientes.123");
            adminC.cargarArchivo();
            adminC.añadirCliente(c);
            adminC.escribirArchivo();//*/

            cBoxmodel.addElement(c);
            jCbox_carrosCliente.setModel(cBoxmodel);

            String[] nRow = {jT_nombreCliente.getText(),
                jT_apellidoCliente.getText(),
                jSp_edadCliente.getValue().toString(),
                jCbox_asignarCarroCliente.getSelectedItem().toString() + ","
            };
            jCbox_asignarCarroCliente.removeItemAt(jCbox_asignarCarroCliente.getSelectedIndex());
            tblModel.addRow(nRow);
            jTbl_tablaClientes.setModel(tblModel);
            JOptionPane.showMessageDialog(this, "Se ha añadido un cliente.");
            jT_nombreCliente.setText("");
            jT_apellidoCliente.setText("");
        }
    }//GEN-LAST:event_btn_añadirClienteActionPerformed

    private void jMI_añadirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_añadirClienteActionPerformed
        // TODO add your handling code here:
        jD_añadirCliente.setModal(true);
        jD_añadirCliente.pack();
        jD_añadirCliente.setLocationRelativeTo(this);
        jD_añadirCliente.setVisible(true);
    }//GEN-LAST:event_jMI_añadirClienteActionPerformed

    private void jMI_añadirCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_añadirCarroActionPerformed
        // TODO add your handling code here:
        jD_añadirCarro.setModal(true);
        jD_añadirCarro.pack();
        jD_añadirCarro.setLocationRelativeTo(this);
        jD_añadirCarro.setVisible(true);
    }//GEN-LAST:event_jMI_añadirCarroActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:    
        if (numEmpleados > 3) {
            JOptionPane.showMessageDialog(this, "Solo pueden haber 3 empleados");
        } else {
            jD_añadirEmpleado.setModal(true);
            jD_añadirEmpleado.pack();
            jD_añadirEmpleado.setLocationRelativeTo(this);
            jD_añadirEmpleado.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btn_asignarCarroEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_asignarCarroEmpleadoActionPerformed
        // TODO add your handling code here:
        jD_AsignarCarroEmpleado.setModal(true);
        jD_AsignarCarroEmpleado.pack();
        jD_AsignarCarroEmpleado.setLocationRelativeTo(this);
        jD_AsignarCarroEmpleado.setVisible(true);
    }//GEN-LAST:event_btn_asignarCarroEmpleadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jD_añadirCliente.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jD_añadirCarro.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jD_añadirEmpleado.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jD_AsignarCarroEmpleado.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn_guardarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarEmpleadoActionPerformed
        // TODO add your handling code here:
        if (jT_nombreEmpleado.getText().equals("") || jT_apellido.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Porfavor llene todos los campos.");
        } else if (jTbl_carroParaEmpleado.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un carro para el empleado.");
        } else {
            DefaultComboBoxModel model = (DefaultComboBoxModel) jCbox1.getModel();
            Empleado e = new Empleado(
                    jT_nombreEmpleado.getText(),
                    jT_nombreEmpleado.getText(),
                    Integer.parseInt(jSp_edadEmpleado.getValue().toString()));
            AdministrarEmpleado adminE = new AdministrarEmpleado("./empleados.123");
            numEmpleados++;
            adminE.cargarArchivo();
            adminE.añadirEmpleado(e);
            adminE.escribirArchivo();//*/

            model.addElement(e);
            jCbox1.setModel(model);
            jCbox2.setModel(model);
            jCbox3.setModel(model);

            jTbl_carroParaEmpleado.getSelectedRow();

            String placa = jTbl_carroParaEmpleado.getValueAt(0, 0).toString();
            String tamaño = jTbl_carroParaEmpleado.getValueAt(0, 1).toString();
            int puertas = Integer.parseInt(jTbl_carroParaEmpleado.getValueAt(0, 2).toString());
            int suciedad = Integer.parseInt(jTbl_carroParaEmpleado.getValueAt(0, 3).toString());
            Carro c = new Carro(placa, tamaño, puertas, suciedad);
            e.añadirCarroLavar(c);
            JOptionPane.showMessageDialog(this, "Se ha añadido un empleado.");
            jT_nombreEmpleado.setText("");
            jT_apellido.setText("");
        }
    }//GEN-LAST:event_btn_guardarEmpleadoActionPerformed

    private void btb_aggCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btb_aggCarrosActionPerformed
        // TODO add your handling code here:
        if (jCbox_carrosCliente.getSelectedIndex() >= 1) {
            DefaultTableModel model = (DefaultTableModel) jTbl_carroParaEmpleado.getModel();
            Cliente c = (Cliente) jCbox_carrosCliente.getSelectedItem();
            for (int i = 0; i < c.getCarros().size(); i++) {
                Object[] o = {
                    c.getCarros().get(i).getPlaca(),
                    c.getCarros().get(i).getTamaño(),
                    c.getCarros().get(i).getNumPuertas(),
                    c.getCarros().get(i).getNvlSucio()
                };
                model.addRow(o);
            }//fin for
            jTbl_carroParaEmpleado.setModel(model);
            JOptionPane.showMessageDialog(this, "Se ha añadido un carro.");
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un Cliente");
        }
    }//GEN-LAST:event_btb_aggCarrosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jCbox1.getSelectedIndex() >= 1) {
            DefaultTableModel model = (DefaultTableModel) jTbl1.getModel();

        } else {

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btb_aggCarros;
    private javax.swing.JButton btn_asignarCarroEmpleado;
    private javax.swing.JButton btn_añadirCarro;
    private javax.swing.JButton btn_añadirCliente;
    private javax.swing.JButton btn_guardarEmpleado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jCbox1;
    private javax.swing.JComboBox<String> jCbox2;
    private javax.swing.JComboBox<String> jCbox3;
    private javax.swing.JComboBox<String> jCbox_asignarCarroCliente;
    private javax.swing.JComboBox<String> jCbox_carrosCliente;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JDialog jD_AsignarCarroEmpleado;
    private javax.swing.JDialog jD_añadirCarro;
    private javax.swing.JDialog jD_añadirCliente;
    private javax.swing.JDialog jD_añadirEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMI_añadirCarro;
    private javax.swing.JMenuItem jMI_añadirCliente;
    private javax.swing.JMenu jMI_añadirEmpleado;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar jPb_barra1;
    private javax.swing.JProgressBar jPb_barra2;
    private javax.swing.JProgressBar jPb_barra3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSpinner jSp_edadCliente;
    private javax.swing.JSpinner jSp_edadEmpleado;
    private javax.swing.JSpinner jSp_puertas;
    private javax.swing.JSpinner jSp_suciedad;
    private javax.swing.JTextField jT_apellido;
    private javax.swing.JTextField jT_apellidoCliente;
    private javax.swing.JTextField jT_nombreCliente;
    private javax.swing.JTextField jT_nombreEmpleado;
    private javax.swing.JTextField jT_placa;
    private javax.swing.JTable jTbl1;
    private javax.swing.JTable jTbl2;
    private javax.swing.JTable jTbl3;
    private javax.swing.JTable jTbl_carroParaEmpleado;
    private javax.swing.JTable jTbl_tablaClientes;
    // End of variables declaration//GEN-END:variables
    private int numEmpleados;
    private AdminBarra1 adminB1;
    private AdminBarra2 adminB2;
    private AdminBarra3 adminB3;
}
